FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_MAPBOX_TOKEN
ARG VITE_USUARIOS_URL
ARG VITE_MASCOTAS_URL
ARG VITE_REPORTES_URL
ARG VITE_REPORTS_MAP_URL
ARG VITE_MIS_REPORTES_URL

ENV VITE_MAPBOX_TOKEN=$VITE_MAPBOX_TOKEN
ENV VITE_USUARIOS_URL=$VITE_USUARIOS_URL
ENV VITE_MASCOTAS_URL=$VITE_MASCOTAS_URL
ENV VITE_REPORTES_URL=$VITE_REPORTES_URL
ENV VITE_REPORTS_MAP_URL=$VITE_REPORTS_MAP_URL
ENV VITE_MIS_REPORTES_URL=$VITE_MIS_REPORTES_URL

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
